cache: npm
language: node_js
node_js:
    - lts/*

stages:
    - cache
    - checks
    - release

jobs:
    include:
        - stage: cache
          name: "Warm up cache"
          script: echo "Warming up npm cache"
        - stage: checks
          name: "Build"
          script:
              - npm run build
              - npm run bundlesize
        - stage: checks
          name: "Typescript"
          script: npm run tsc
        - stage: checks
          name: "Unit tests"
          script: npm test
        - stage: checks
          name: "Check formatting"
          script: npm run format:check
        - stage: release
          name: "Publish demo to Github Pages"
          if: branch = master
          script: skip
          deploy:
              provider: pages
              skip-cleanup: true
              github-token: $GITHUB_TOKEN
              keep-history: true
              local-dir: demo
              on:
                  branch: master
        - stage: release
          name: Release to npm
          if: branch = master AND commit_message =~ /(feat|fix|BREAKING CHANGE)/
          script:
              - npm run build
              - npx semantic-release
